/// <reference path="Objects/fpslabel.ts" />
/// <reference path="Objects/sprite.ts" />
/// <reference path="Objects/tilesprite.ts" />
/// <reference path="Objects/velocity.ts" />
/// <reference path="game.ts" />
/// <reference path="global.d.ts" />
/// <reference path="Objects/baseobject.ts" />
/// <reference path="physics/basiccollisionhandler.ts" />
/// <reference path="physics/icollisionhandler.d.ts" />
//# sourceMappingURL=_references.js.map